### ISSUE TITLE
Button press and Card exit side

### ISSUE THREAD

**Issue by srelard** [bugs-and-errors/tinder_swipecard#1]
How can I implement the command when a button is pressed or check when the card is leaving the left or right side?

**Comment by abhisunkewar** [comment]
Thanks @srelard! I'll work on this for the next update. Meanwhile, feel free to implement this and open a PR.

**Comment by abhisunkewar** [comment]
Hey @srelard! We've added support for custom action functions in `v0.2.0` of the library. You can now set the actions - `onLike`, `onDislike`, `onSuperLike`, `onRefresh` to your liking. 

Thank you for your patience.
